on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello from GitHub  Actions @carlogilmar!"
